permadeath_codes = {'adventure': '65',
                    'exploration': '72',
                    'roguelike': '66'}

diffiiculty_codes = {'easy': '33',
                     'normal': '6',
                     'nighmare': '26',
                     'insane': '36',
                     'madness': '227'}

campaign_codes = {'arena': '46',
                  'infinite': '24',
                  'majeyal': '2',
                  'orcs': '67402'}

version_codes = {'1.7.6': '1191241',
                 '1.7.5': '1165973',
                 '1.7.4': '699172',
                 '1.7.3': '673614',
                 '1.7.2': '545529',
                 '1.7.1': '545101',
                 '1.7.0': '532301',}

race_codes = {'Higher': '3',
              'Cornac': '8',
              'Dwarf': '9',
              'Thalore': '13',
              'Shalore': '18',
              'Halfling': '21',
              'Skeleton': '25',
              'Ghoul': '42',
              'Yeek': '47',
              'Runic Golem': '50',
              'Lich': '74',
              'Tutorial Stats': '78',
              'Tutorial Basic': '81',
              'Wight': '82',
              'Wraith': '84',
              'Humanoid': '86',
              'Doomelf': '23296',
              'Drem': '104070',
              'Krog': '133993',
              'Kruk Yeti': '67413',
              'Ogre': '37515',
              'Orc': '114',
              'Whitehoof': '67497'}

class_codes ={'Wyrmic': '4',
            'Archmage': '7',
            'Cursed': '10',
            'Rogue': '12',
            'Archer': '14',
            'Berserker': '16',
            'Summoner': '17',
            'Alchemist': '19',
            'Anorithil': '20',
            'Arcane Blade': '22',
            'Shadowblade': '23',
            'Sun Paladin': '27',
            'Doomed': '29',
            'Geomancer': '30',
            'Reaver': '31',
            'Pyromancer': '32',
            'Corruptor': '34',
            'Tutorial Adventurer': '39',
            'Paradox Mage': '43',
            'Mindslayer': '48',
            'Temporal Warden': '49',
            'Golem': '51',
            'Brawler': '56',
            'Necromancer': '68',
            'Stone Warden': '70',
            'Marauder': '71',
            'Bulwark': '80',
            'Tourist': '83',
            'Ranger': '91',
            'Illusionist': '92',
            'Monk': '97',
            'Magebow': '98',
            'Barbarian': '99',
            'Solipsist': '102',
            'Soul Stealer': '103',
            'Adventurer': '104',
            'Gardener': '107',
            'Charlatan': '108',
            'Phoenix Knight': '112',
            'Elementist': '124',
            'Werebeast': '126',
            'Rodent': '129',
            'Human': '131'}